DATA	SEGMENT PUBLIC 'DATA'
DATA	ENDS

DGROUP	GROUP DATA

CODE	SEGMENT 'CODE'
	ASSUME CS:CODE,DS:DGROUP,SS:DGROUP

	PUBLIC IAND
IAND	PROC FAR
	PUSH BP
	MOV BP,SP
	LES BX,DWORD PTR [BP+10]
	MOV AX,ES:[BX]
	MOV DX,ES:[BX]+2
	LES BX,DWORD PTR [BP+6]
	AND AX,ES:[BX]
	AND DX,ES:[BX]+2
	MOV SP,BP
	POP BP
	RET 08H
	IAND ENDP
CODE	ENDS
	END
