DATA	SEGMENT PUBLIC 'DATA'
DATA	ENDS

DGROUP	GROUP DATA

CODE	SEGMENT 'CODE'
	ASSUME CS:CODE,DS:DGROUP,SS:DGROUP

	PUBLIC IEOR
IEOR	PROC FAR
	PUSH BP
	MOV BP,SP
	LES BX,DWORD PTR [BP+10]
	MOV AX,ES:[BX]
	MOV DX,ES:[BX]+2
	LES BX,DWORD PTR [BP+6]
	XOR AX,ES:[BX]
	XOR DX,ES:[BX]+2
	MOV SP,BP
	POP BP
	RET 08H
	IEOR ENDP
CODE	ENDS
	END
